// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockExtractor is an autogenerated mock type for the Extractor type
type MockExtractor struct {
	mock.Mock
}

type MockExtractor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExtractor) EXPECT() *MockExtractor_Expecter {
	return &MockExtractor_Expecter{mock: &_m.Mock}
}

// Extract provides a mock function with given fields: htmlBytes
func (_m *MockExtractor) Extract(htmlBytes []byte) (int64, string, bool) {
	ret := _m.Called(htmlBytes)

	if len(ret) == 0 {
		panic("no return value specified for Extract")
	}

	var r0 int64
	var r1 string
	var r2 bool
	if rf, ok := ret.Get(0).(func([]byte) (int64, string, bool)); ok {
		return rf(htmlBytes)
	}
	if rf, ok := ret.Get(0).(func([]byte) int64); ok {
		r0 = rf(htmlBytes)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func([]byte) string); ok {
		r1 = rf(htmlBytes)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func([]byte) bool); ok {
		r2 = rf(htmlBytes)
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// MockExtractor_Extract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extract'
type MockExtractor_Extract_Call struct {
	*mock.Call
}

// Extract is a helper method to define mock.On call
//   - htmlBytes []byte
func (_e *MockExtractor_Expecter) Extract(htmlBytes interface{}) *MockExtractor_Extract_Call {
	return &MockExtractor_Extract_Call{Call: _e.mock.On("Extract", htmlBytes)}
}

func (_c *MockExtractor_Extract_Call) Run(run func(htmlBytes []byte)) *MockExtractor_Extract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockExtractor_Extract_Call) Return(_a0 int64, _a1 string, _a2 bool) *MockExtractor_Extract_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockExtractor_Extract_Call) RunAndReturn(run func([]byte) (int64, string, bool)) *MockExtractor_Extract_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExtractor creates a new instance of MockExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExtractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExtractor {
	mock := &MockExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
