// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockFetcher is an autogenerated mock type for the Fetcher type
type MockFetcher struct {
	mock.Mock
}

type MockFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFetcher) EXPECT() *MockFetcher_Expecter {
	return &MockFetcher_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function with given fields: ctx, rawURL
func (_m *MockFetcher) Fetch(ctx context.Context, rawURL string) ([]byte, string, error) {
	ret := _m.Called(ctx, rawURL)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []byte
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, string, error)); ok {
		return rf(ctx, rawURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, rawURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, rawURL)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, rawURL)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockFetcher_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockFetcher_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - rawURL string
func (_e *MockFetcher_Expecter) Fetch(ctx interface{}, rawURL interface{}) *MockFetcher_Fetch_Call {
	return &MockFetcher_Fetch_Call{Call: _e.mock.On("Fetch", ctx, rawURL)}
}

func (_c *MockFetcher_Fetch_Call) Run(run func(ctx context.Context, rawURL string)) *MockFetcher_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFetcher_Fetch_Call) Return(_a0 []byte, _a1 string, _a2 error) *MockFetcher_Fetch_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockFetcher_Fetch_Call) RunAndReturn(run func(context.Context, string) ([]byte, string, error)) *MockFetcher_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFetcher creates a new instance of MockFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFetcher {
	mock := &MockFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
