// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	kafka_go "github.com/segmentio/kafka-go"

	mock "github.com/stretchr/testify/mock"
)

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

type MockWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriter) EXPECT() *MockWriter_Expecter {
	return &MockWriter_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockWriter) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWriter_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockWriter_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockWriter_Expecter) Close() *MockWriter_Close_Call {
	return &MockWriter_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockWriter_Close_Call) Run(run func()) *MockWriter_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWriter_Close_Call) Return(_a0 error) *MockWriter_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWriter_Close_Call) RunAndReturn(run func() error) *MockWriter_Close_Call {
	_c.Call.Return(run)
	return _c
}

// WriteMessages provides a mock function with given fields: ctx, msgs
func (_m *MockWriter) WriteMessages(ctx context.Context, msgs ...kafka_go.Message) error {
	_va := make([]interface{}, len(msgs))
	for _i := range msgs {
		_va[_i] = msgs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WriteMessages")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...kafka_go.Message) error); ok {
		r0 = rf(ctx, msgs...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWriter_WriteMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteMessages'
type MockWriter_WriteMessages_Call struct {
	*mock.Call
}

// WriteMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - msgs ...kafka_go.Message
func (_e *MockWriter_Expecter) WriteMessages(ctx interface{}, msgs ...interface{}) *MockWriter_WriteMessages_Call {
	return &MockWriter_WriteMessages_Call{Call: _e.mock.On("WriteMessages",
		append([]interface{}{ctx}, msgs...)...)}
}

func (_c *MockWriter_WriteMessages_Call) Run(run func(ctx context.Context, msgs ...kafka_go.Message)) *MockWriter_WriteMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]kafka_go.Message, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(kafka_go.Message)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockWriter_WriteMessages_Call) Return(_a0 error) *MockWriter_WriteMessages_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWriter_WriteMessages_Call) RunAndReturn(run func(context.Context, ...kafka_go.Message) error) *MockWriter_WriteMessages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWriter creates a new instance of MockWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriter {
	mock := &MockWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
